### ISSUE TITLE
Is there a way to proceed with this course using Apple silicon macs?

### ISSUE THREAD

**Issue by jojonarte** [theurbanpenguin/lfcs#1]
I couldn't make the virtual box work it seems it's not fully supported for silicon chips.

**Comment by theurbanpenguin** [comment]
The course and EXAM are based on Intel. You can install Ubuntu yourself on Silicon MACs using the ARM download but virtualisation is still early days on these systems. Parallels works and that was all that worked for a while bit both VirtualBox and VMware Fusion are available on Silicon. You can also use online cloud providers to provision systems for you. Many offer a free access for some time

**Comment by jojonarte** [comment]
I was able to proceed using `UTM`
